# Generated by Django 3.2.3 on 2021-05-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagoModel',
            fields=[
                ('pagoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('pagoIdPasarela', models.IntegerField(db_column='id_pasarela', unique=True)),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': 'pagos',
            },
        ),
    ]
