# Generated by Django 3.2.2 on 2021-05-23 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoModel',
            fields=[
                ('pagoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('pagoIdPasarela', models.IntegerField(db_column='id_pasarela', help_text='id de pago', unique=True)),
                ('pagoPrecio', models.DecimalField(db_column='monto', decimal_places=2, help_text='precio del curso', max_digits=5, verbose_name='precio del curso')),
                ('pagoEstado', models.CharField(db_column='estado', help_text='estado del pago', max_length=10, verbose_name='estado')),
                ('pagoDetalleEstado', models.CharField(db_column='detalle_estado', help_text='detalle del estado del pago', max_length=10)),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='PagosCursoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoIdFK', models.ForeignKey(db_column='curso_id', help_text='id de curso', on_delete=django.db.models.deletion.CASCADE, to='cursos.cursomodel', verbose_name='id de curso')),
                ('pagoIdFK', models.ForeignKey(db_column='pago_id', help_text='id de pago', on_delete=django.db.models.deletion.CASCADE, to='pagos.pagomodel', verbose_name='id de pago')),
            ],
            options={
                'verbose_name': 'pago_curso',
                'verbose_name_plural': 'pago_curso',
                'db_table': 'pagos_curso',
            },
        ),
    ]
