# Generated by Django 3.2.3 on 2021-05-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomodel',
            name='pagoDetalleEstado',
            field=models.CharField(db_column='detalle_estado', default='--', help_text='Detalle del estado', max_length=10),
        ),
        migrations.AddField(
            model_name='pagomodel',
            name='pagoEstado',
            field=models.CharField(db_column='estado', default='--', help_text='Estado del pago', max_length=10, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='pagomodel',
            name='pagoPrecio',
            field=models.DecimalField(db_column='monto', decimal_places=2, default=0.0, help_text='precio del curso', max_digits=5, verbose_name='precio del curso'),
        ),
    ]
