# Generated by Django 3.2.2 on 2021-05-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomodel',
            name='cursosItems',
            field=models.ManyToManyField(through='pagos.PagosCursoModel', to='cursos.CursoModel'),
        ),
        migrations.AlterField(
            model_name='pagomodel',
            name='pagoEstado',
            field=models.CharField(choices=[('', 'Sin estado'), ('IN', 'En Proceso'), ('A', 'Aprobado'), ('R', 'Rechazado')], db_column='estado', default='', help_text='estado del pago', max_length=2, verbose_name='estado'),
        ),
    ]
