# Generated by Django 3.2.2 on 2021-05-23 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomodel',
            name='clientes_id',
            field=models.ForeignKey(db_column='cliente_id', help_text='id del cliente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.clientemore', verbose_name='id del cliente'),
        ),
    ]
