# Generated by Django 3.2.3 on 2021-05-14 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_auto_20210514_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosCursoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagoIdFK', models.ForeignKey(db_column='pago_id', help_text='id de pago', on_delete=django.db.models.deletion.CASCADE, to='pagos.pagomodel', verbose_name='id de pago')),
            ],
            options={
                'verbose_name': 'pago_curso',
                'verbose_name_plural': 'pago_curso',
                'db_table': 'pagos_curso',
            },
        ),
    ]
