# Generated by Django 3.2.2 on 2021-05-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_auto_20210529_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagomodel',
            name='pagoIdPasarela',
            field=models.CharField(db_column='id_pasarela', default='none', help_text='id de pago', max_length=50),
        ),
    ]
