# Generated by Django 3.2.2 on 2021-05-19 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursomodel',
            name='profesor',
            field=models.ForeignKey(db_column='profesor_id', help_text='Profesor del curso', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesorCursos', to='usuarios.profesormore', verbose_name='profesor'),
        ),
    ]
