# Generated by Django 3.2.2 on 2021-05-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursomodel',
            old_name='descripionCurso',
            new_name='descripcionCurso',
        ),
    ]
